api/urls.py
from rest_framework.routers import DefaultRouter

from api.views import BookReviewViewSet

app_name = "api"

router = DefaultRouter()
router.register('reviews', BookReviewViewSet, basename='review')
urlpatterns = router.urls

goodreads/urls.py
from django.urls import path
from django.urls import include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from .views import home_page
from .views import landing_page


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='landing_page'),
    path('books/', include("books.urls")),
    path('home/', home_page, name='home_page'),
    path('users/', include('users.urls'), name="users"),

    path("api/", include("api.urls")),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import LoginView
from users.views import LogoutView
from users.views import ProfileView
from users.views import RegisterView
from users.views import ProfileUpdateView

app_name = "users"

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("register", RegisterView.as_view(), name="register"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="def_pic.jpg")

users/forms.py
from django import forms

from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ("username", "first_name", "last_name", "email", "password")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture') # noqa

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['username'].widget.attrs.update({'class': 'form-control'}) # NOQA

users/views.py
from django.views import View
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib.auth import logout
from users.forms import UserUpdateForm
from users.forms import UserCreateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }

        return render(request, "users/register.html", context=context)

    def post(self, request):
        create_form = UserCreateForm(request.POST)

        if create_form.is_valid():
            user = create_form.save()
            user.set_password(create_form.cleaned_data['password'])
            user.save()
            return redirect('users:login')
        else:
            context = {
                "form": create_form
            }
            return render(request, "users/register.html", context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()

        return render(request, "users/login.html", {"login_form": login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, "You have successfully logged in :)")

            return redirect("landing_page")

        else:
            return render(request, "users/login.html", {"login_form": login_form}) # noqa


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "users/profile.html", {"user": request.user})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully loged out :)")
        return redirect("landing_page")


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, "users/profile_edit.html", {"form": user_update_form}) # noqa

    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
            )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, "You have succesfully updated your profile ;)") # noqa

            return redirect("users:profile")

        return render(request, "users/profile_edit.html", {"form": user_update_form}) # noqa

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login Page{% endblock %}

{% block content %}
<h3>Login</h3>
<div class="row">
    <div class="col-4">
        <form method="post">
            {% csrf_token %}
            {{ login_form | crispy }}
            <button class="btn btn-primary" type="submit">Log in</button> <span class="ms-3">No account ? Then, <a
                    href="{% url 'users:register' %}">get registered</a></span>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}Profile Page{% endblock %}

{% block content %}

<div class=" image d-flex flex-column justify-content-center align-items-center">
    <button class="btn btn-secondary">
        <img class="profile-pic" alt="Profile picture" src="{{ user.profile_picture.url }}">
    </button>
    <span class="name mt-3">{{ user.first_name }} {{ user.last_name }}</span>
    <span class="idd">@{{ user.username }}</span>
    <span class="idd">{{ user.email }}</span>
    <div class=" d-flex mt-2"> <a class="btn btn-dark" href="{% url 'users:profile-edit' %}">edit profile</a> </div>
    <div class=" px-2 rounded mt-4 date "> <span class="join">Joined {{ user.date_joined | date:"M d, Y" }}</span>
    </div>
</div>

{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h3>Edit Profile</h3>

<div class="row">
    <div class="col-4">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form | crispy}}

            <button class="btn btn-primary">Save changes</button>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register Page{% endblock %}

{% block content %}
<h3>Register</h3>
<div class="row">
    <div class="col-4">
        <form method="post" action="{% url 'users:register'%}">
            {% csrf_token %}

            {{ form | crispy }}

            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}